bookcat/api_home/forms.py
from flask_wtf import FlaskForm
from wtforms import  StringField, SubmitField, IntegerField, FloatField
from wtforms.validators import DataRequired


class EditBookForm(FlaskForm): ## This is subclassing
    title = StringField('Title', validators=[DataRequired()])
    format = StringField('Format', validators=[DataRequired()])
    num_pages = StringField('Pages',validators=[DataRequired()])
    submit = SubmitField('Update Book')



class CreateBookForm(FlaskForm): ## This is subclassing
    title = StringField('Title', validators=[DataRequired()])
    author= StringField('Author', validators=[DataRequired()])
    rating = FloatField('Rating', validators=[DataRequired()])
    format = StringField('Format', validators=[DataRequired()])
    img_url = StringField('Image', validators=[DataRequired()])
    num_pages = IntegerField('Pages', validators=[DataRequired()])
    pub_id = StringField('Publisher ID', validators=[DataRequired()])
    submit = SubmitField('Create Book')

bookcat/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask import g
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_bcrypt import Bcrypt

app = Flask('__name__')
app.config.from_pyfile('config.py')

db = SQLAlchemy(app)

bootstrap = Bootstrap(app)

login_manager = LoginManager(app)
login_manager.login_view = 'authentication.do_the_login'
login_manager.session_protection = 'strong'    #flask
bcrypt = Bcrypt(app)

@app.route('/api/')
def api():
    return 'api'


@app.before_request  #This a decorator this is executed before every request, here we can check sessions
def get_something(): #after_request and etc are other decorators
    g.string = '<br> This code ran before my request<br>'

from bookcat.auth import  authentication
from bookcat.api_home import home
app.register_blueprint(home)
app.register_blueprint(authentication)

bookcat/api_home/__init__.py
from flask import Blueprint

home = Blueprint('api_home', __name__, url_prefix=('/api'), template_folder='templates')

from bookcat.api_home.views import *

bookcat/api_home/views.py
from bookcat.api_home import home
from flask import session
from flask import g
from flask import render_template, flash, request, redirect, url_for
from flask_login import login_required
from bookcat.api_home.forms import EditBookForm, CreateBookForm

@home.route('/home/')
def get_home():
    return 'Welcome To Home'

@home.route('/home/add/publications')
def add_data_publication():
    from bookcat.shared_models import Publication
    p2 = Publication("Paramount Press")
    p3 = Publication("Oracle Books Inc")
    p4 = Publication("Vintage Books and Comics")
    p5 = Publication("Trolls Press")
    p6 = Publication("Broadway Press")
    p7 = Publication("Downhill Publishers")
    p8 = Publication("Kingfisher Inc")

    from bookcat import db
    db.session.add_all([p2, p3, p4, p5, p6, p7, p8])
    db.session.commit()

    return 'Added Data in Publication Table'

@home.route('/home/add/books')
def add_data_books():
    from bookcat.shared_models import Books
    b1 = Books("Miky's Delivery Service", "William Dobelli", 3.9, "ePub", "broom-145379.svg", 123, 1)
    b2 = Books("The Secret Life of Walter Kitty", "Kitty Stiller", 4.1, "Hardcover", "cat-150306.svg", 133, 1)
    b3 = Books("The Empty Book of Life", "Roy Williamson", 4.2, "eBook", "book-life-34063.svg", 153, 1)
    b4 = Books("Life After Dealth", "Nikita Kimmel", 3.8, "Paperback", "mummy-146868.svg", 175, 2)
    b5 = Books("Sali The Dali", "Charles Rowling", 4.6, "Hardcover", "el-salvador-dali-889515.jpg", 253, 2)
    b6 = Books("Taming Dragons", "James Vonnegut", 4.5, "MassMarket Paperback", "dragon-23164.svg", 229, 2)
    b7 = Books("The Singing Magpie", "Oscar Steinbeck", 5, "Hardcover", "magpie-147852.svg", 188, 3)
    b8 = Books("Mr. Incognito", "Amelia Funke", 4.2, "Hardcover", "incognito-160143.svg", 205, 3)
    b9 = Books("A Dog without purpose", "Edgar Dahl", 4.8, "MassMarket Paperback", "dog-159271.svg", 300, 4)
    b10 = Books("A Frog's Life", "Herman Capote", 3.9, "MassMarket Paperback", "amphibian-150342.svg", 190, 4)
    b11 = Books("Logan Returns", "Margaret Elliot", 4.6, "Hardcover", "wolf-153648.svg", 279, 5)
    b12 = Books("Thieves of Kaalapani", "Mohit Gustav", 4.1, "Paperback", "boat-1296201.svg", 270, 5)
    b13 = Books("As Men Thinketh", "Edward McPhee", 4.5, "Paperback", "cranium-2028555.svg", 124, 6)
    b14 = Books("Mathematics of Music", "Mary Turing", 4.5, "Hardcover", "music-306008.svg", 120, 6)
    b15 = Books("The Mystery of Mandalas", "Jack Morrison", 4.2, "Paperback", "mandala-1817599.svg", 221, 6)
    b16 = Books("The Sacred Book of Kairo", "Heidi Zimmerman", 3.8, "ePub", "book-1294676.svg", 134, 7)
    b17 = Books("Love is forever, As Long as it lasts", "Kovi O'Hara", 4.5, "Hardcover", "love-2026554.svg", 279, 8)
    b18 = Books("Order in Chaos", "Wendy Sherman", 3.5, "MassMarket Paperback", "chaos-1769656.svg", 140, 8)

    from bookcat import db
    db.session.add_all([b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15, b16, b17, b18])
    db.session.commit()

    return 'Added Data in Books Table'

@home.route('/home/get/books/')
def get_books():

    from bookcat.shared_models import Books
    all = Books.query.all()
    book1 = Books.query.first()
    book2 = Books.query.get(2)  #return on the basis of primary key passed in get(2)
    book3 = Books.query.filter_by(id=1).first() #filtering on the basis of a field
    book4 = Books.query.order_by(Books.title).all()

    return book3.title


@home.route('/home/update/books')
def update_books():

    from bookcat.shared_models import Books
    book1 = Books.query.get(16)
    book1.format = 'hardcover2'

    from bookcat import db
    db.session.commit()

    book1 = Books.query.get(16)
    return book1.format


@home.route('/home/session/')
def session_data():

    if 'name' not in session:         #refrences secret_key in config.py so this attribute must exist in config.py
        session['name'] = 'Ali'
    return "Session added" + g.string


@home.route('/home/books')
def display_books():
    from bookcat.shared_models import Books
    books = Books.query.all()
    return render_template('home.html', books=books)

@home.route('/home/books/publisher/<publisher_id>')
def display_publisher(publisher_id):
    from bookcat.shared_models import Publication
    from bookcat.shared_models import Books

    publisher = Publication.query.filter_by(id=publisher_id).first()
    publisher_books = Books.query.filter_by(pub_id=publisher.id).all()

    return render_template('publisher.html', publisher=publisher, publisher_books=publisher_books)


@home.route('/book/delete/<book_id>', methods=['GET','POST'])
@login_required
def delete_book(book_id):
    from bookcat.shared_models import Books

    book = Books.query.get(book_id)

    if request.method == 'POST':

        from bookcat import db
        db.session.delete(book)
        db.session.commit()
        flash('Book Deleted Successfully')
        return redirect(url_for('api_home.display_books'))
    return render_template('delete_book.html', book=book, book_id=book.id)

@home.route('/edit/book/<book_id>', methods=['GET', 'POST'])
@login_required
def edit_book(book_id):
    from bookcat.shared_models import Books

    book = Books.query.get(book_id)
    form = EditBookForm(obj=book)  #Pre-populates the data in the form
    if form.validate_on_submit():
        book.title =form.title.data
        book.format =form.format.data
        book.num_pages = form.num_pages.data

        from bookcat import db
        db.session.add(book)
        db.session.commit()
        flash('Book Updated Successfully')
        return redirect(url_for('api_home.display_books'))
    return render_template('edit_book.html', form=form)


@home.route('/create/book/<pub_id>', methods=['GET', 'POST'])
@login_required
def create_book(pub_id):
    from bookcat.shared_models import Books

    form = CreateBookForm()

    if form.validate_on_submit():
        book =Books(title=form.title.data, author=form.author.data, avg_rating=form.rating.data,format=form.format.data,
                    image=form.img_url.data, num_pages=form.num_pages.data, pub_id=form.pub_id.data)

        from bookcat import db
        db.session.add(book)
        db.session.commit()
        flash('Book added Successfully')
        return redirect(url_for('api_home.display_publisher', publisher_id=book.pub_id))
    return render_template('create_book.html', form=form)

bookcat/templates/create_book.html
{%extends 'layout.html' %}

{% block content %}
        <div class="container">
            <h4 style="...">Create a Book Here</h4>
            <hr><br>
            {{ form.hidden_tag() }} <!-- This is to protect csrf (cross site scripting)attacks-->
            {{wtf.quick_form(form)}}
        </div>
{% endblock %}

bookcat/templates/delete_book.html
{%extends 'layout.html' %}

{%block content%}

    <div class="container">

        <h4 style="margin-left: 45px">Delete the book ?</h4>
        <hr>
            <p style="margin-left: 45px">

                Book ID: {{book.id}} <br>
                Title: {{book.title}} <br>
                Author: {{book.author}}

            </p>
        <br>

        <form action="{{url_for('api_home.delete_book',book_id=book.id)}}" method="POST" style="margin-left: 45px">

             <button type="submit" class="btn btn-sm btn-primary">delete</button>
        </form>

    </div>

{%endblock%}

bookcat/templates/edit_book.html
{%extends 'layout.html' %}

{% block content %}
        <div class="container">
            <h4 style="...">Edit Book Here</h4>
            <hr><br>
            {{ form.hidden_tag() }} <!-- This is to protect csrf (cross site scripting)attacks-->
            {{wtf.quick_form(form)}}
        </div>
{% endblock %}

bookcat/templates/home.html
{% extends 'layout.html' %}


{% block content %}
        <div class="container books">
            <div class="row">
                    {%for book in books%}
                        <div class="col-md-4">
                            <img src="/static/images/{{book.image}}" alt="book-img" height="200" width="180">
                            <h4>Title: {{book.title}}</h4>
                            <p>Authors: {{book.author}}</p>
                            <p>Avg Rating: {{book.avg_rating}}</p>
                            <p>Format: {{book.format}}</p>
                            <p>No of Pages: {{book.num_pages}}</p>
                            <p><a href="{{url_for('api_home.display_publisher', publisher_id=book.pub_id)}}">Publisher ID: {{book.pub_id}} </a> </p>
                            <span class="label label-success"><a href="{{url_for('api_home.create_book',pub_id=book.pub_id)}}" style="color: floralwhite">create</a></span>
                            <span class="label label-primary"><a href="{{url_for('api_home.edit_book',book_id=book.id)}}" style="color: floralwhite">edit</a></span>
                            <span class="label label-info"><a href="{{url_for('api_home.delete_book',book_id=book.id)}}" style="color: floralwhite">delete</a></span>
                            <br>
                         </div>
                     {% endfor %}
            </div>
        </div>
{% endblock %}

bookcat/templates/layout.html
{% import "bootstrap/wtf.html" as wtf%}


<!DOCTYPE html>

<html lang="en">

<head>
    {% block head %}
    <meta charset="UTF-8">
    <Title>Books</Title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    {%endblock head%}
</head>


{% block body %}

<body>

    <div class="wrapper">

        {% block navbar %}
        <nav class="navbar navbar-inverse">
            <div class="container">
                <a class="navbar navbar-text" href="{{url_for('api_home.display_books')}}">
                    <h3 class="title">The Books Around The Corner</h3>
                </a>
                <ul class="nav navbar-nav pull-right">

                    <li><a href="{{url_for('api_home.display_books')}}">Home </a> </li>
                    <li><a href="{{url_for('authentication.register_user')}}">Register </a> </li>
                    <li>{%if current_user.is_authenticated%}
                        <a href="{{url_for('authentication.log_out_user')}}">SignOut </a> </li>
                        {%else%}
                        <a href="{{url_for('authentication.do_the_login')}}">SignIn </a>
                        {%endif%}
                    </li>

                    <li>
                        <a href="">
                        {%if current_user.is_authenticated%}
                           LoggedIn as  <b style="color:deepink">{{current_user.user_name.title()}}</b>
                        {%else%}
                            Not LoggedIn
                        {%endif%}
                        </a>
                    </li>

                </ul>
            </div>
        </nav>
    {%endblock navbar%}

          {% for message in get_flashed_messages() %}  <!-- This can display alert message on any web page in flask-->

            <div class="container alert alert-info">
                <button type="button" class="close" data-dismiss="alert"></button>

                {{message}}
            </div>

          {%endfor%}


        {#empty block for custom content#}
    {%block content%}  {%endblock content %}

    {%block footer%}
    <footer>
        <div class="container ftr">
            <hr>
            <p class="text-center small">The Shop Around The Corner | 2017</p>
        </div>
    </footer>
    {%endblock footer%}
    </div>
</body>

{%endblock body%}

</html>

bookcat/templates/login.html
{% extends 'layout.html' %}

{%block title%} Sign In {% endblock%}

{%block content%}
    <div class="contain form">

        <h4>Login Here</h4>
        <br><br>
        {{ wtf.quick_form(form) }}
    </div>
{%endblock content%}

bookcat/templates/publisher.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <Title>Books</Title>
</head>

<body>

    <h4> Books by {{publisher.name}}</h4>
    <ol>
        {%for book in publisher_books%}
         <li type="1">

             {{book.title}} by {{book.author}}
         </li>

        {%endfor%}
    </ol>


</body>


</html>

bookcat/templates/registration.html
{%extends 'layout.html' %}

{% block content %}
        <h4 class="form">Register Here</h4>
        <div class="container">
            <hr><br>

            {{ form.hidden_tag() }} <!-- This is to protect csrf (cross site scripting)attacks-->

            {{wtf.quick_form(form)}}
        </div>

{% endblock %}

bookcat/templates/registration_old.html
{%extends 'layout.html' %}

{%block content %}
        <h4 class="form">Register Here</h4>
        <div class="container">
            <hr>
            <br>
            <form action="/register/" method="post">
                {{form.hidden_tag()}}

            {% if form.email.errors %}
                <div class="form-group required has-error">
                     {{form.name.label}}
                    <span>&nbsp;</span>
                    <span>&nbsp;</span>
                    <span>&nbsp;</span>
                    <span>&nbsp;</span>
                     {{form.name}}
                </div>

                <div class="form-group">
                     {{form.email.label}}
                      <span>&nbsp;</span>
                      <span>&nbsp;</span>
                      <span>&nbsp;</span>
                      <span>&nbsp;</span>
                     {{form.email}}
                </div>

                {%for error in form.email.errors%}
                <p class="help-block"> {{error}} </p>
                {% endfor %}

            {%else%}
                 <div class="form-group required">
                     {{form.name.label}}
                    <span>&nbsp;</span>
                    <span>&nbsp;</span>
                    <span>&nbsp;</span>
                    <span>&nbsp;</span>
                     {{form.name}}
                </div>


                <div class="form-group">
                     {{form.email.label}}
                      <span>&nbsp;</span>
                      <span>&nbsp;</span>
                      <span>&nbsp;</span>
                      <span>&nbsp;</span>
                     {{form.email}}
                </div>

            {%endif%}


                <div class="form-group">
                     {{form.password.label}}
                     {{form.password}}
                </div>


                <div class="form-group">
                     {{form.confirm.label}}
                      <span>&nbsp;</span>
                     {{form.confirm}}
                </div>


                <div class="form-group">
                    {{form.submit(class='btn btn-primary')}}
                </div>

            </form>
        </div>

{% endblock %}